// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const createMedia = `-- name: CreateMedia :exec
INSERT INTO media (
    id, post_id, mime, s3_key,
    created_at, deleted_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMediaParams struct {
	ID        string
	PostID    sql.NullString
	Mime      string
	S3Key     string
	CreatedAt string
	DeletedAt sql.NullString
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) error {
	_, err := q.db.ExecContext(ctx, createMedia,
		arg.ID,
		arg.PostID,
		arg.Mime,
		arg.S3Key,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	return err
}

const getMedia = `-- name: GetMedia :one
SELECT id, post_id, mime, s3_key, created_at, deleted_at
FROM media
WHERE id = ?
`

func (q *Queries) GetMedia(ctx context.Context, id string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Mime,
		&i.S3Key,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaByS3Key = `-- name: GetMediaByS3Key :one
SELECT id, post_id, mime, s3_key, created_at, deleted_at
FROM media
WHERE s3_key = ?
`

func (q *Queries) GetMediaByS3Key(ctx context.Context, s3Key string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMediaByS3Key, s3Key)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Mime,
		&i.S3Key,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaByS3Keys = `-- name: GetMediaByS3Keys :many
SELECT id, post_id, mime, s3_key, created_at, deleted_at FROM media
WHERE s3_key IN (/*SLICE:keys*/?)
`

func (q *Queries) GetMediaByS3Keys(ctx context.Context, keys []string) ([]Medium, error) {
	query := getMediaByS3Keys
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Mime,
			&i.S3Key,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedia = `-- name: UpdateMedia :exec
UPDATE media
SET post_id = ?, mime = ?, s3_key = ?,
created_at = ?, deleted_at = ?
WHERE id = ?
`

type UpdateMediaParams struct {
	PostID    sql.NullString
	Mime      string
	S3Key     string
	CreatedAt string
	DeletedAt sql.NullString
	ID        string
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) error {
	_, err := q.db.ExecContext(ctx, updateMedia,
		arg.PostID,
		arg.Mime,
		arg.S3Key,
		arg.CreatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	return err
}
