// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Post struct {
	ID              string
	Title           string
	Slug            string
	Description     string
	MarkdownContent sql.NullString
	HtmlContent     sql.NullString
	Status          string
	CreatedAt       string
	UpdatedAt       string
}
