// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Medium struct {
	ID        string
	PostID    sql.NullString
	Mime      string
	S3Key     string
	CreatedAt string
	DeletedAt sql.NullString
}

type Post struct {
	ID              string
	Title           string
	Slug            sql.NullString
	Description     string
	MarkdownContent sql.NullString
	HtmlContent     sql.NullString
	Status          string
	CreatedAt       string
	UpdatedAt       string
}
