// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (
    id, title, slug, description,
    markdown_content, html_content,
    status, created_at, updated_at
) VALUES (?,?,?,?,?,?,?,?,?)
`

type CreatePostParams struct {
	ID              string
	Title           string
	Slug            sql.NullString
	Description     string
	MarkdownContent sql.NullString
	HtmlContent     sql.NullString
	Status          string
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.MarkdownContent,
		arg.HtmlContent,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, title, slug, description, markdown_content, html_content, status, created_at, updated_at
FROM posts
WHERE id = ?
`

func (q *Queries) GetPost(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.MarkdownContent,
		&i.HtmlContent,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, title, slug, description, markdown_content, html_content, status, created_at, updated_at
FROM posts
WHERE slug = ?
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug sql.NullString) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.MarkdownContent,
		&i.HtmlContent,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPosts = `-- name: ListAllPosts :many
SELECT id, title, slug, description, markdown_content, html_content, status, created_at, updated_at
FROM posts
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAllPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.MarkdownContent,
			&i.HtmlContent,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, title, slug, description, markdown_content, html_content, status, created_at, updated_at
FROM posts
WHERE status = 'published'
`

func (q *Queries) ListPublishedPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.MarkdownContent,
			&i.HtmlContent,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts 
SET title = ?, slug = ?, description = ?,
markdown_content = ?, html_content = ?,
status = ?, created_at = ?, updated_at = ?
WHERE id = ?
`

type UpdatePostParams struct {
	Title           string
	Slug            sql.NullString
	Description     string
	MarkdownContent sql.NullString
	HtmlContent     sql.NullString
	Status          string
	CreatedAt       string
	UpdatedAt       string
	ID              string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.MarkdownContent,
		arg.HtmlContent,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
