// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// GuestView shows the public site in a frame at a chosen viewport width,
// so the admin can browse it the way a visitor would.
func GuestView() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"guest-bar\"><a class=\"back-link\" href=\"/admin\">&larr; all posts</a><div class=\"guest-bar__widths\" role=\"group\" aria-label=\"viewport width\"><button type=\"button\" class=\"admin-action\" data-width=\"390px\">phone</button> <button type=\"button\" class=\"admin-action\" data-width=\"768px\">tablet</button> <button type=\"button\" class=\"admin-action\" data-width=\"100%\" aria-pressed=\"true\">desktop</button></div><a class=\"admin-action\" href=\"/\" target=\"_blank\" rel=\"noopener\">open in new tab &nearr;</a></div><div class=\"guest-stage\"><iframe class=\"guest-frame\" name=\"guest\" src=\"/\" title=\"site as a guest sees it\"></iframe></div><script>\n\t\t\t(() => {\n\t\t\t\tconst frame = document.querySelector(\".guest-frame\");\n\t\t\t\tconst buttons = document.querySelectorAll(\".guest-bar__widths button\");\n\t\t\t\tfor (const b of buttons) {\n\t\t\t\t\tb.addEventListener(\"click\", () => {\n\t\t\t\t\t\tframe.style.width = b.dataset.width;\n\t\t\t\t\t\tfor (const o of buttons) o.setAttribute(\"aria-pressed\", o === b);\n\t\t\t\t\t});\n\t\t\t\t}\n\t\t\t})();\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Guest view", nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
